#!/bin/bash
if [ -z "$1" ]; then
  echo "directory path not present"
  exit 1
fi
if [ -z "$2" ]; then
  echo "size threshold not present"
  exit 1
fi
if [ -z "$3" ]; then
  echo "time threshold not present, defaulting to one year"
  time=525600
else
  time=$3  
fi
api=haoly8_yRPVQIm58PU3LpoBXyOCDIy7f;
#set time for one year by default
for param in  png jpg jpeg
do
   #find all jpg and png files for this parameter
   find "$1" -name "*.${param}" -type f -size "+${2}" -mmin "-${time}" | sort > "temp${param}.txt"
   if [ ! -s temp${param}.txt ]; then
      echo "No $param files found to process"
   else 
      echo "$param files found. Processing..."
		
   	varL=1
   	#loop through all files 
   	while read p; do
	  #upload file to  	
	  JSON=`curl -i --user api:$api --data-binary @$p https://api.tinypng.com/shrink 2>/dev/null  `; 
	  echo "JSON is ${JSON}";
          #find the location of the converted file
	  URL=${JSON/*url\":\"/};
	  URL=${URL/\"*/};

    	  echo "URL is $URL";

	  curl $URL> ${varL}_tmp 2>/dev/null
          #check if file is converted and has a valid size 
	  if [[ $(find ${varL}_tmp -type f -size +1k 2>/dev/null) ]]; then
           cat ${varL}_tmp > $p		
	   echo "${p} updated."
	  else
	   echo "${p} NOT updated."
          fi 
	  rm -f ${varL}_tmp
          ((varL++))
  	done < temp${param}.txt

  fi
  rm -rf temp${param}.txt
done  

