#!/bin/bash
echo "Converting PNG files using TinyPNG.org (by Voormedia http://voormedia.com)";
api=haoly8_yRPVQIm58PU3LpoBXyOCDIy7f;
for param in  png jpg
do
   #find all jpg and png files for this parameter
        find "$1" -name "*.$param" -type f -size +20k | sort > "temp$param.txt"
  varL=1
  #delete previous versions of files
  #loop through all files 
  while read p; do
	  JSON=`curl -i --user api:$api --data-binary @$p https://api.tinypng.com/shrink 2>/dev/null  `; 
echo $JSON;
	  URL=${JSON/*url\":\"/};
	  URL=${URL/\"*/};

    echo "$URL";

	  curl $URL>${p} 2>/dev/null
	
	  echo "${p} updated.";
  done < temp$param.txt

done  

