#!/bin/bash
if [ -z "$1" ]; then
  echo "directory path not present"
  exit 1
fi
if [ -z "$2" ]; then
  echo "size threshold not present"
  exit 1
fi
echo "Converting PNG files using TinyPNG.org (by Voormedia http://voormedia.com)";
api=haoly8_yRPVQIm58PU3LpoBXyOCDIy7f;
for param in  png jpg
do
   #find all jpg and png files for this parameter
        find "$1" -name "*.${param}" -type f -size $2 | sort > "temp${param}.txt"
  varL=1
  #loop through all files 
  while read p; do
	  #upload file to  	
	  JSON=`curl -i --user api:$api --data-binary @$p https://api.tinypng.com/shrink 2>/dev/null  `; 
#	  echo "JSON is ${JSON}";
	  URL=${JSON/*url\":\"/};
	  URL=${URL/\"*/};

    	  echo "URL is $URL";

	  curl $URL> ${varL}_tmp 2>/dev/null
	  if [[ $(find ${varL}_tmp -type f -size +1k 2>/dev/null) ]]; then
           cat ${varL}_tmp > $p		
	   echo "${p} updated."
	  else
	   echo "${p} NOT updated."
          fi 
	  #rm ${varL}_tmp
          ((varL++))
  done < temp${param}.txt

done  

